
export const GET_BURGER = "GET_BURGER";
export const GET_BURGER_SUCCESS = "GET_BURGER_SUCCESS";
export const GET_BURGER_FAIL = "GET_BURGER_FAIL";

export const GET_BURGER_SETTINGS = "GET_BURGER_SETTINGS";
export const GET_BURGER_SETTINGS_SUCCESS = "GET_BURGER_SETTINGS_SUCCESS";
export const GET_BURGER_SETTINGS_FAIL = "GET_BURGER_SETTINGS_FAIL";

export const INGRADIENTS_BURGER = "INGRADIENTS_BURGER";

export const CLOSE_MODAL_WINDOW = "CLOSE_MODAL_WINDOW";
